version: 2.1

executors:
  bb:
    docker:
      - image: babashka/babashka:0.2.5

commands:
  setup-git:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "12:ba:f4:f4:c5:ad:80:73:b0:2c:da:a9:36:5b:95:a0"
      - run:
          name: Install & config git
          command: |
            apt update
            apt install --no-install-recommends -yy git ssh-client
            git config --global user.email "ci-build@polymeris.dev"
            git config --global user.name "ci-build"
  push-data:
    parameters:
      message:
        type: string
    steps:
      - run:
          name: Push to git
          command: |
            git add -f out/*
            git checkout -B data
            git commit -m "<< parameters.message >> [ci skip]"
            git push -u origin data --force

jobs:
  test:
    executor: bb
    steps:
      - checkout
      - run: src/afp_quotes.clj test
      - run: src/btg_quotes.clj test

  update-quotes:
    executor: bb
    steps:
      - setup-git
      - checkout
      - run: src/afp_quotes.clj
      - run: src/btg_quotes.clj
      - push-data:
          message: Update quotes

workflows:
  version: 2
  test-and-update:
    jobs:
      - test
      - update-quotes:
          requires:
            - test
          filters:
            branches:
              only: master
  nightly-update:
    triggers:
      - schedule:
          cron: "25 7 * * 1-6"
          filters:
            branches:
              only:
                - master
    jobs:
      - update-quotes
